export const relativePaths = {
    "landingPage" : "/",
    "authentification" : "/authentification",
    "resetPassword" : "/resetPassword",
    "verifyEmail" : "/verifyEmail",
    "userDashboard" : "/userDashboard",
    "adminDashboard" : "/adminDashboard",
    "allUsers" :"allUsers",
    "addUser" :"addUser",
    "settings" :"settings",
    "profile" :"profile",

    "gatewayList" :"gatewayList",
    "weather" : "weather" ,
    "editGateway" :"editGateway",
    "addGateway" :"addGateway",
    "governorateList" :"governorateList",
    "editGovernorate" :"editGovernorate",
    "addGovernorate" :"addGovernorate",
    "localityList" :"localityList",
    "editLocality" :"editLocality",
    "sensorValue" :"sensorValue",
    "charts" : "charts"
    // "" :"",
}
export const absolutePaths = {
    "landingPage" : "/",
    "authentification" : "/authentification",
    "resetPassword" : "/resetPassword",
    "verifyEmail" : "/verifyEmail",
    "userDashboard" : "/home",
    "adminDashboard" : "/dashboard",
    "allUsers" :"/dashboard/allUsers",
    "addUser" :"/dashboard/addUser",
    "settings" :"/dashboard/settings",
    "profile" :"/dashboard/profile",

    "gatewayList" :"/userDashboard/gatewayList",
    "weather" : "/userDashboard/weather",
    "editGateway" :"/userDashboard/editGateway",
    "addGateway" :"/userDashboard/addGateway",
    "governorateList" :"/userDashboard/governorateList",
    "editGovernorate" :"/userDashboard/editGovernorate",
    "addGovernorate" :"/userDashboard/addGovernorate",
    "localityList" :"/userDashboard/localityList",
    "editLocality" :"/userDashboard/editLocality",
    "sensorValue" :"/userDashboard/sensorValue",
    "charts" : "/userDashboard/charts"
    // "" :"",
    // "" :"",
}